plugins:
    - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
      spec: "@yarnpkg/plugin-workspace-tools"
    - path: .yarn/plugins/@ojkelly/plugin-all.cjs
      spec: "https://yarn.build/latest"
    - path: .yarn/plugins/@yarnpkg/plugin-constraints.cjs
      spec: "@yarnpkg/plugin-constraints"
yarnPath: .yarn/releases/yarn-3.2.4.cjs
nodeLinker: node-modules
