name: CI

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  publish:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
          cache: "npm"
      - run: npm i -g npm@8
      - run: npm ci
      - run: npm run bootstrap
      - run: npm run npm
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  release:
    needs: [publish]
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: softprops/action-gh-release@v1
        with:
          body_path: ./CHANGELOG.md
