name: CI

on:
    pull_request:
    push:
        branches:
            - "main"

jobs:
    check:
        runs-on: ubuntu-20.04
        strategy:
            fail-fast: false
            matrix:
                cmd: ["test", "lint", "prettier"]
        name: ${{ matrix.node-version }} - ${{ matrix.cmd }}
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: "16"
                  cache: "npm"
            - run: npm i -g npm@8
            - run: npm ci
            - run: npm run bootstrap
            - run: npm rebuild
            - run: npm run build
            - run: npm run ${{ matrix.cmd }}
    format:
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v2
              with:
                  repository: ${{ github.event.pull_request.head.repo.full_name }}
                  ref: ${{ github.event.pull_request.head.ref }}
            - uses: actions/setup-node@v2
              with:
                  node-version: "16"
                  cache: "npm"
            - run: npm i -g npm@8
            - run: npm ci
            - run: npm run bootstrap
            - run: npm rebuild
            - run: npm run prettier:write || exit 0
            - run: git diff-index --quiet HEAD --
            - if: failure() && github.event_name == 'pull_request'
              uses: EndBug/add-and-commit@v8
              with:
                  author_name: "GitHub Actions"
                  author_email: "actions@github.com"
                  message: "Ran Prettier"
