name: CI

on:
  pull_request:
  push:
    branches:
      - 'main'

jobs:
  check:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        cmd: ['build', 'test', 'lint', 'prettier:check']
    name: ${{ matrix.cmd }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - uses: actions/cache@v2
        with:
          path: |
            node_modules
            */*/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
      - run: npm i -g npm@7
      - run: npm i
      - run: npm exec -- lerna bootstrap
      - run: npm run ${{ matrix.cmd }}
