name: 'Lint PR Title'

on:
  pull_request:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
      - reopened

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
